### ISSUE TITLE
Please do not add repositories (this also can break builds with Gradle 6.8+)

### ISSUE THREAD

**Issue by Vampire** [ph4r05/javacard-gradle-plugin#2]
Your plugin adds MavenCentral as repository.
That is very bad practice.
Please stop doing this in your plugin.
We for example want all dependencies to be served from our internal repository and not depend on MavenCentral.

Now with Gradle 6.8 there is a way to centrally define the repositories for all projects in the builds within the settings script.
This feature also contains a property to set the `repositoriesMode` and as we don't want any other repositories but all needed dependencies in our internal repository, it is set to `FAIL_ON_PROJECT_REPOS`.
Now as soon as your plugin is applied, the build fails as your plugin tries to add MavenCentral to the build.

It should always be in the hands of the build author to define where dependencies are taken from and not silently in plugins.
Please at least add an option to disable this undesirable behaviour.

**Comment by ph4r05** [comment]
I will think about adding an option to disable inclusion of these repositories. 

The plugin mainly adds private maven repositories as it depends on artefacts not yet published in the maven central. When author publishes them to the central, adding those repos can be completely removed. But for time being, it is not possible to remove those maven repos.

It does not seem right to use no-repos setting as a default and then requiring user of the plugin to add these private maven repos to the buildscript maven repo dependencies.

**Comment by Vampire** [comment]
Are you maybe confusing this project with another one?
I had a quick look at the code again.
You add two repositories.
1. Maven Central unconditionally
2. http://dl.bintray.com/bertrandmartel/maven for getting an old version of jcardsim with other coordinates than the default ones added and you also only add this repository if a config option is explicitly set to `true`

There are no other private repositories or anything you should actually need except you want it explicitly and then you can also say where to get it from.

All I asked for is not adding Maven Central automatically or make it configurable.
This is theoretically a breaking changes, yes, but who does not have Maven Central as repository or maybe JCenter (which afair forwards to Maven Central for things it does not have itself), except for people that are required to only use internal repos and care for the dependencies to be available there.

And even then, an off-switch would be enough for me, though it really is bad practice to silently add this unconditionally.

**Comment by ph4r05** [comment]
Aah I see, sure, this is possible, I will add it to my TODOlist. This is part of the legacy code, from the parent repository this was forked from. I was thinking about removing this altogether.

**Comment by ph4r05** [comment]
Should be fixed in v1.8.0
