### ISSUE TITLE
Provide an own configuration for adding gptool to

### ISSUE THREAD

**Issue by Vampire** [ph4r05/javacard-gradle-plugin#4]
Currently the `gptool` dependency has to be added to the main source set runtime dependencies.
(You document to use `implementation` though `runtimeOnly` would be better, as it is semantically more correct and does not pollute the compile class path which makes compilation slower)
But it actually is not a runtime dependency of the code you are developing in the main source set.
Please consider adding another configuration in your plugin that is then used as class path for running the gptool instead of requiring to pollute the runtime class path of the main source set.

You could for the time being support both and maybe print a deprecation warning if someone adds it to the main source set, so that this can be removed in some distant future release. :-)

**Comment by Vampire** [comment]
While I think about it, you should even add the dependencies yourself.
The usual pattern is, that you add the configuration from your plugin and set the things you need as `defaultDependencies`.
This way if someone wants a different set of dependencies e. g. different version, he can declare his own, if he does not add anything to the configuration your default dependencies are used.
This could even be combined with a `gptoolVersion` property on your extension that is used when adding the default dependencies. That way if someone just wants a different version he can simply set it on your extension instead of having to declare the dependencies explicitly.

**Comment by ph4r05** [comment]
Should be fixed in v1.8.0
