### ISSUE TITLE
debugGpPro is not considered by script task tasks

### ISSUE THREAD

**Issue by Vampire** [ph4r05/javacard-gradle-plugin#5]
If you add script tasks like
```kt
javacard {
    scripts {
        task {
            name = "foo"
            scripts = listOf("foo")
        }
    }
}
```
then the GpExec task is unconditionally configured with `-d` and the config flag is ignored:
https://github.com/ph4r05/javacard-gradle-plugin/blob/master/gradle-javacard/src/main/groovy/com/klinec/gradle/javacard/JavaCardPlugin.groovy#L106

**Comment by ph4r05** [comment]
Should be fixed in v1.8.0

**Comment by Vampire** [comment]
Great, when can I exect the 1.8 release? :-)

**Comment by ph4r05** [comment]
@Vampire it is released already. Give it a try. Readme page shows that version 1.8.0 should be released in maven repo, I tested it and it worked fine for my projects. 

However, there were some issues with Sonatype repo, I had to upload, close and release the repo like 15 times, it was failing all the time with timeouts and verification errors. But it should be fine by now.

**Comment by Vampire** [comment]
Don't you release to the Gradle Plugin Portal anymore? o_O
It still has 1.7.2: https://plugins.gradle.org/plugin/com.klinec.gradle.javacard

**Comment by Vampire** [comment]
And you also didn't push an 1.8.0 tag actually, that's why I thought it is not released yet, otherwise I would have thought it is pending verification

**Comment by ph4r05** [comment]
> Don't you release to the Gradle Plugin Portal anymore? o_O
> It still has 1.7.2: https://plugins.gradle.org/plugin/com.klinec.gradle.javacard

I don't feel like updating it there. I already forgot how to do that, last time there were some issues with the plugin acceptance, so it is too much effort at the moment. Maven repo is primary source for now.

**Comment by ph4r05** [comment]
I've updated also at plugin portal (it seems I have gradle task for that)

**Comment by Vampire** [comment]
Great, thanks, I was about to open a separate issue about that.
Because this has multiple implications.
For example:
- People might use an outdated version as it is the current one on plugin central (we indeed did use 1.7.2)
- If you deploy to plugin central with the plugin as you did now, it also publishes the "marker" dependency that allows resolution of `plugins { id("com.klinec.gradle.javacard") version "1.8.0" }` to resolve to the needed dependency with the code, without it you need to map the id to the code dependency using `resolutionStrategy` in settings script manually to be able to use the plugin in a plugins block
- The plugin protal is the default repository for resolving plugins from plugins block
- Using the plugins block is especially handy when using the Kotlin DSL, as then static accessors are generated for plugins that are applied using the plugins block, so that you can write `javacard { /* ... */ }` instead of `configure<com.klinec.gradle.javacard.extension.JavaCard> { /* ... */ }`
